//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lorax.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public partial class LoraxParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, IDENTIFIER=8, 
		T_NULL=9, T_BOOL=10, T_TRUE=11, T_FALSE=12, INTEGER=13, FLOAT=14, STRING=15, 
		TREE_ACCESS_LEFT=16, TREE_ACCESS_RIGHT=17, TREE_ACCESS_PARENT=18, TREE_ACCESS_VALUE=19, 
		WS=20;
	public const int
		RULE_value = 0, RULE_treeAccess = 1, RULE_treeLiteral = 2, RULE_treeChildren = 3, 
		RULE_treeChild = 4, RULE_nodeValue = 5, RULE_tupleAccess = 6, RULE_treeAccessOps = 7, 
		RULE_treeAccessTraversor = 8, RULE_tupleAccessOp = 9, RULE_tuple = 10, 
		RULE_primitive = 11, RULE_literal = 12;
	public static readonly string[] ruleNames = {
		"value", "treeAccess", "treeLiteral", "treeChildren", "treeChild", "nodeValue", 
		"tupleAccess", "treeAccessOps", "treeAccessTraversor", "tupleAccessOp", 
		"tuple", "primitive", "literal"
	};

	private static readonly string[] _LiteralNames = {
		null, "'['", "']'", "':'", "'@'", "'<'", "','", "'>'", null, "'Null'", 
		null, "'True'", "'False'", null, null, null, "'/'", "'\\'", "'^'", "'$'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, "IDENTIFIER", "T_NULL", 
		"T_BOOL", "T_TRUE", "T_FALSE", "INTEGER", "FLOAT", "STRING", "TREE_ACCESS_LEFT", 
		"TREE_ACCESS_RIGHT", "TREE_ACCESS_PARENT", "TREE_ACCESS_VALUE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Lorax.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static LoraxParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public LoraxParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public LoraxParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(LoraxParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TreeLiteralContext treeLiteral() {
			return GetRuleContext<TreeLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TupleContext tuple() {
			return GetRuleContext<TupleContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrimitiveContext primitive() {
			return GetRuleContext<PrimitiveContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 0, RULE_value);
		try {
			State = 30;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 26;
				Match(IDENTIFIER);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 27;
				treeLiteral();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 28;
				tuple();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 29;
				primitive();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TreeAccessContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TreeLiteralContext treeLiteral() {
			return GetRuleContext<TreeLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TreeAccessOpsContext treeAccessOps() {
			return GetRuleContext<TreeAccessOpsContext>(0);
		}
		public TreeAccessContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_treeAccess; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterTreeAccess(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitTreeAccess(this);
		}
	}

	[RuleVersion(0)]
	public TreeAccessContext treeAccess() {
		TreeAccessContext _localctx = new TreeAccessContext(Context, State);
		EnterRule(_localctx, 2, RULE_treeAccess);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32;
			treeLiteral();
			State = 33;
			treeAccessOps();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TreeLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NodeValueContext nodeValue() {
			return GetRuleContext<NodeValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TreeChildrenContext treeChildren() {
			return GetRuleContext<TreeChildrenContext>(0);
		}
		public TreeLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_treeLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterTreeLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitTreeLiteral(this);
		}
	}

	[RuleVersion(0)]
	public TreeLiteralContext treeLiteral() {
		TreeLiteralContext _localctx = new TreeLiteralContext(Context, State);
		EnterRule(_localctx, 4, RULE_treeLiteral);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 35;
			nodeValue();
			State = 36;
			Match(T__0);
			State = 38;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__2) | (1L << T__4) | (1L << IDENTIFIER) | (1L << T_NULL) | (1L << T_BOOL) | (1L << INTEGER) | (1L << FLOAT) | (1L << STRING))) != 0)) {
				{
				State = 37;
				treeChildren();
				}
			}

			State = 40;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TreeChildrenContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TreeChildContext[] treeChild() {
			return GetRuleContexts<TreeChildContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TreeChildContext treeChild(int i) {
			return GetRuleContext<TreeChildContext>(i);
		}
		public TreeChildrenContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_treeChildren; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterTreeChildren(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitTreeChildren(this);
		}
	}

	[RuleVersion(0)]
	public TreeChildrenContext treeChildren() {
		TreeChildrenContext _localctx = new TreeChildrenContext(Context, State);
		EnterRule(_localctx, 6, RULE_treeChildren);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 43;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__4) | (1L << IDENTIFIER) | (1L << T_NULL) | (1L << T_BOOL) | (1L << INTEGER) | (1L << FLOAT) | (1L << STRING))) != 0)) {
				{
				State = 42;
				treeChild();
				}
			}

			State = 45;
			Match(T__2);
			State = 47;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__4) | (1L << IDENTIFIER) | (1L << T_NULL) | (1L << T_BOOL) | (1L << INTEGER) | (1L << FLOAT) | (1L << STRING))) != 0)) {
				{
				State = 46;
				treeChild();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TreeChildContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NodeValueContext nodeValue() {
			return GetRuleContext<NodeValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TreeLiteralContext treeLiteral() {
			return GetRuleContext<TreeLiteralContext>(0);
		}
		public TreeChildContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_treeChild; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterTreeChild(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitTreeChild(this);
		}
	}

	[RuleVersion(0)]
	public TreeChildContext treeChild() {
		TreeChildContext _localctx = new TreeChildContext(Context, State);
		EnterRule(_localctx, 8, RULE_treeChild);
		try {
			State = 51;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 49;
				nodeValue();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 50;
				treeLiteral();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NodeValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(LoraxParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TupleContext tuple() {
			return GetRuleContext<TupleContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrimitiveContext primitive() {
			return GetRuleContext<PrimitiveContext>(0);
		}
		public NodeValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nodeValue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterNodeValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitNodeValue(this);
		}
	}

	[RuleVersion(0)]
	public NodeValueContext nodeValue() {
		NodeValueContext _localctx = new NodeValueContext(Context, State);
		EnterRule(_localctx, 10, RULE_nodeValue);
		try {
			State = 56;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 53;
				Match(IDENTIFIER);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 54;
				tuple();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 55;
				primitive();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TupleAccessContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TupleAccessOpContext tupleAccessOp() {
			return GetRuleContext<TupleAccessOpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TupleContext tuple() {
			return GetRuleContext<TupleContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(LoraxParser.IDENTIFIER, 0); }
		public TupleAccessContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tupleAccess; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterTupleAccess(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitTupleAccess(this);
		}
	}

	[RuleVersion(0)]
	public TupleAccessContext tupleAccess() {
		TupleAccessContext _localctx = new TupleAccessContext(Context, State);
		EnterRule(_localctx, 12, RULE_tupleAccess);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__4:
				{
				State = 58;
				tuple();
				}
				break;
			case IDENTIFIER:
				{
				State = 59;
				Match(IDENTIFIER);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 62;
			tupleAccessOp();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TreeAccessOpsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TreeAccessTraversorContext treeAccessTraversor() {
			return GetRuleContext<TreeAccessTraversorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TREE_ACCESS_VALUE() { return GetToken(LoraxParser.TREE_ACCESS_VALUE, 0); }
		public TreeAccessOpsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_treeAccessOps; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterTreeAccessOps(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitTreeAccessOps(this);
		}
	}

	[RuleVersion(0)]
	public TreeAccessOpsContext treeAccessOps() {
		TreeAccessOpsContext _localctx = new TreeAccessOpsContext(Context, State);
		EnterRule(_localctx, 14, RULE_treeAccessOps);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64;
			treeAccessTraversor();
			State = 66;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==TREE_ACCESS_VALUE) {
				{
				State = 65;
				Match(TREE_ACCESS_VALUE);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TreeAccessTraversorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TREE_ACCESS_LEFT() { return GetToken(LoraxParser.TREE_ACCESS_LEFT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TREE_ACCESS_RIGHT() { return GetToken(LoraxParser.TREE_ACCESS_RIGHT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TREE_ACCESS_PARENT() { return GetToken(LoraxParser.TREE_ACCESS_PARENT, 0); }
		public TreeAccessTraversorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_treeAccessTraversor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterTreeAccessTraversor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitTreeAccessTraversor(this);
		}
	}

	[RuleVersion(0)]
	public TreeAccessTraversorContext treeAccessTraversor() {
		TreeAccessTraversorContext _localctx = new TreeAccessTraversorContext(Context, State);
		EnterRule(_localctx, 16, RULE_treeAccessTraversor);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TREE_ACCESS_LEFT) | (1L << TREE_ACCESS_RIGHT) | (1L << TREE_ACCESS_PARENT))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TupleAccessOpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTEGER() { return GetToken(LoraxParser.INTEGER, 0); }
		public TupleAccessOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tupleAccessOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterTupleAccessOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitTupleAccessOp(this);
		}
	}

	[RuleVersion(0)]
	public TupleAccessOpContext tupleAccessOp() {
		TupleAccessOpContext _localctx = new TupleAccessOpContext(Context, State);
		EnterRule(_localctx, 18, RULE_tupleAccessOp);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			Match(T__3);
			State = 71;
			Match(INTEGER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TupleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PrimitiveContext[] primitive() {
			return GetRuleContexts<PrimitiveContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrimitiveContext primitive(int i) {
			return GetRuleContext<PrimitiveContext>(i);
		}
		public TupleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_tuple; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterTuple(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitTuple(this);
		}
	}

	[RuleVersion(0)]
	public TupleContext tuple() {
		TupleContext _localctx = new TupleContext(Context, State);
		EnterRule(_localctx, 20, RULE_tuple);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 73;
			Match(T__4);
			State = 82;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IDENTIFIER) | (1L << T_NULL) | (1L << T_BOOL) | (1L << INTEGER) | (1L << FLOAT) | (1L << STRING))) != 0)) {
				{
				State = 74;
				primitive();
				State = 79;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 75;
					Match(T__5);
					State = 76;
					primitive();
					}
					}
					State = 81;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 84;
			Match(T__6);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrimitiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(LoraxParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public PrimitiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primitive; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterPrimitive(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitPrimitive(this);
		}
	}

	[RuleVersion(0)]
	public PrimitiveContext primitive() {
		PrimitiveContext _localctx = new PrimitiveContext(Context, State);
		EnterRule(_localctx, 22, RULE_primitive);
		try {
			State = 88;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 86;
				Match(IDENTIFIER);
				}
				break;
			case T_NULL:
			case T_BOOL:
			case INTEGER:
			case FLOAT:
			case STRING:
				EnterOuterAlt(_localctx, 2);
				{
				State = 87;
				literal();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_NULL() { return GetToken(LoraxParser.T_NULL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode T_BOOL() { return GetToken(LoraxParser.T_BOOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(LoraxParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT() { return GetToken(LoraxParser.FLOAT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTEGER() { return GetToken(LoraxParser.INTEGER, 0); }
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.EnterLiteral(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILoraxListener typedListener = listener as ILoraxListener;
			if (typedListener != null) typedListener.ExitLiteral(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 24, RULE_literal);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T_NULL) | (1L << T_BOOL) | (1L << INTEGER) | (1L << FLOAT) | (1L << STRING))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,20,93,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,1,0,1,0,1,0,1,0,3,0,
		31,8,0,1,1,1,1,1,1,1,2,1,2,1,2,3,2,39,8,2,1,2,1,2,1,3,3,3,44,8,3,1,3,1,
		3,3,3,48,8,3,1,4,1,4,3,4,52,8,4,1,5,1,5,1,5,3,5,57,8,5,1,6,1,6,3,6,61,
		8,6,1,6,1,6,1,7,1,7,3,7,67,8,7,1,8,1,8,1,9,1,9,1,9,1,10,1,10,1,10,1,10,
		5,10,78,8,10,10,10,12,10,81,9,10,3,10,83,8,10,1,10,1,10,1,11,1,11,3,11,
		89,8,11,1,12,1,12,1,12,0,0,13,0,2,4,6,8,10,12,14,16,18,20,22,24,0,2,1,
		0,16,18,2,0,9,10,13,15,93,0,30,1,0,0,0,2,32,1,0,0,0,4,35,1,0,0,0,6,43,
		1,0,0,0,8,51,1,0,0,0,10,56,1,0,0,0,12,60,1,0,0,0,14,64,1,0,0,0,16,68,1,
		0,0,0,18,70,1,0,0,0,20,73,1,0,0,0,22,88,1,0,0,0,24,90,1,0,0,0,26,31,5,
		8,0,0,27,31,3,4,2,0,28,31,3,20,10,0,29,31,3,22,11,0,30,26,1,0,0,0,30,27,
		1,0,0,0,30,28,1,0,0,0,30,29,1,0,0,0,31,1,1,0,0,0,32,33,3,4,2,0,33,34,3,
		14,7,0,34,3,1,0,0,0,35,36,3,10,5,0,36,38,5,1,0,0,37,39,3,6,3,0,38,37,1,
		0,0,0,38,39,1,0,0,0,39,40,1,0,0,0,40,41,5,2,0,0,41,5,1,0,0,0,42,44,3,8,
		4,0,43,42,1,0,0,0,43,44,1,0,0,0,44,45,1,0,0,0,45,47,5,3,0,0,46,48,3,8,
		4,0,47,46,1,0,0,0,47,48,1,0,0,0,48,7,1,0,0,0,49,52,3,10,5,0,50,52,3,4,
		2,0,51,49,1,0,0,0,51,50,1,0,0,0,52,9,1,0,0,0,53,57,5,8,0,0,54,57,3,20,
		10,0,55,57,3,22,11,0,56,53,1,0,0,0,56,54,1,0,0,0,56,55,1,0,0,0,57,11,1,
		0,0,0,58,61,3,20,10,0,59,61,5,8,0,0,60,58,1,0,0,0,60,59,1,0,0,0,61,62,
		1,0,0,0,62,63,3,18,9,0,63,13,1,0,0,0,64,66,3,16,8,0,65,67,5,19,0,0,66,
		65,1,0,0,0,66,67,1,0,0,0,67,15,1,0,0,0,68,69,7,0,0,0,69,17,1,0,0,0,70,
		71,5,4,0,0,71,72,5,13,0,0,72,19,1,0,0,0,73,82,5,5,0,0,74,79,3,22,11,0,
		75,76,5,6,0,0,76,78,3,22,11,0,77,75,1,0,0,0,78,81,1,0,0,0,79,77,1,0,0,
		0,79,80,1,0,0,0,80,83,1,0,0,0,81,79,1,0,0,0,82,74,1,0,0,0,82,83,1,0,0,
		0,83,84,1,0,0,0,84,85,5,7,0,0,85,21,1,0,0,0,86,89,5,8,0,0,87,89,3,24,12,
		0,88,86,1,0,0,0,88,87,1,0,0,0,89,23,1,0,0,0,90,91,7,1,0,0,91,25,1,0,0,
		0,11,30,38,43,47,51,56,60,66,79,82,88
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
