//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lorax.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILoraxListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LoraxBaseListener : ILoraxListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] LoraxParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] LoraxParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.treeAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTreeAccess([NotNull] LoraxParser.TreeAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.treeAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTreeAccess([NotNull] LoraxParser.TreeAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.treeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTreeLiteral([NotNull] LoraxParser.TreeLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.treeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTreeLiteral([NotNull] LoraxParser.TreeLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.treeChildren"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTreeChildren([NotNull] LoraxParser.TreeChildrenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.treeChildren"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTreeChildren([NotNull] LoraxParser.TreeChildrenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.treeChild"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTreeChild([NotNull] LoraxParser.TreeChildContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.treeChild"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTreeChild([NotNull] LoraxParser.TreeChildContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.nodeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNodeValue([NotNull] LoraxParser.NodeValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.nodeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNodeValue([NotNull] LoraxParser.NodeValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.tupleAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleAccess([NotNull] LoraxParser.TupleAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.tupleAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleAccess([NotNull] LoraxParser.TupleAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.treeAccessOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTreeAccessOps([NotNull] LoraxParser.TreeAccessOpsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.treeAccessOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTreeAccessOps([NotNull] LoraxParser.TreeAccessOpsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.treeAccessTraversor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTreeAccessTraversor([NotNull] LoraxParser.TreeAccessTraversorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.treeAccessTraversor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTreeAccessTraversor([NotNull] LoraxParser.TreeAccessTraversorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.tupleAccessOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleAccessOp([NotNull] LoraxParser.TupleAccessOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.tupleAccessOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleAccessOp([NotNull] LoraxParser.TupleAccessOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.tuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTuple([NotNull] LoraxParser.TupleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.tuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTuple([NotNull] LoraxParser.TupleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.primitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitive([NotNull] LoraxParser.PrimitiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.primitive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitive([NotNull] LoraxParser.PrimitiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LoraxParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] LoraxParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LoraxParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] LoraxParser.LiteralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
